import {
  LayoutDashboard,
  ShoppingCart,
  ArrowLeftRight,
  Boxes,
  Truck,
  Factory,
  Landmark,
  ShieldCheck,
  Files,
  ListChecks,
  ChartNoAxesCombined,
  ChartColumn,
  SlidersHorizontal,
  Users,
  Settings,
  LifeBuoy,
  Globe,
} from 'lucide-react';
export const modules = [
  { key: 'dashboard', label: 'Dashboard', icon: LayoutDashboard, items: [] },
  {
    key: 'sales',
    label: 'Sales & Export',
    icon: Globe,
    items: [
      ['SALES', 'orders', 'Sales Orders'],
      ['SALES', 'invoices', 'Commercial Invoices'],
      ['CUSTOMERS', 'customers', 'Customer Accounts'],
    ],
  },
  {
    key: 'purchase',
    label: 'Purchase',
    icon: ShoppingCart,
    items: [
      ['PURCHASE', 'purchase-orders', 'Purchase Orders'],
      ['PURCHASE', 'bills', 'Expense Bills'],
      ['PARTNERS', 'vendors', 'Vendors'],
    ],
  },
  { key: 'import', label: 'Import', icon: ArrowLeftRight, items: [] },
  {
    key: 'inventory',
    label: 'Inventory',
    icon: Boxes,
    items: [
      ['STOCK', 'stock', 'Stock Overview'],
      ['STOCK', 'movements', 'Stock Movements'],
      ['MASTERS', 'products', 'Products'],
      ['MASTERS', 'warehouses', 'Warehouses'],
    ],
  },
  {
    key: 'logistics',
    label: 'Logistics',
    icon: Truck,
    items: [['OPERATIONS', 'orders', 'Shipment Overview']],
  },
  { key: 'production', label: 'Production', icon: Factory, items: [] },
  {
    key: 'finance',
    label: 'Finance',
    icon: Landmark,
    items: [
      ['WORKING CAPITAL', 'receivables', 'Receivables'],
      ['WORKING CAPITAL', 'payables', 'Payables'],
      ['ACCOUNTING', 'journal', 'General Ledger'],
      ['ACCOUNTING', 'cash', 'Cash & Bank'],
      ['ACCOUNTING', 'accounts', 'Chart of Accounts'],
    ],
  },
  {
    key: 'compliance',
    label: 'Compliance',
    icon: ShieldCheck,
    items: [['MONITORING', 'exceptions', 'Exception Register']],
  },
  {
    key: 'documents',
    label: 'Documents',
    icon: Files,
    items: [['DOCUMENTS', 'documents', 'Document Centre']],
  },
  {
    key: 'tasks',
    label: 'Tasks & Checklist',
    icon: ListChecks,
    items: [['WORK', 'tasks', 'My Tasks']],
  },
  {
    key: 'costing',
    label: 'Costing & Profitability',
    icon: ChartNoAxesCombined,
    items: [['ANALYSIS', 'profitability', 'Profitability']],
  },
  {
    key: 'reports',
    label: 'Reports',
    icon: ChartColumn,
    items: [
      ['FINANCIAL', 'sales-report', 'Sales Report'],
      ['FINANCIAL', 'trial-balance', 'Trial Balance'],
    ],
  },
  {
    key: 'masters',
    label: 'Masters',
    icon: SlidersHorizontal,
    items: [
      ['BUSINESS PARTNERS', 'customers', 'Customers'],
      ['BUSINESS PARTNERS', 'vendors', 'Vendors'],
      ['PRODUCTS & INVENTORY', 'products', 'Products'],
      ['PRODUCTS & INVENTORY', 'warehouses', 'Warehouses'],
    ],
  },
  {
    key: 'administration',
    label: 'Administration',
    icon: Users,
    items: [
      ['ACCESS', 'users', 'Users & Roles'],
      ['CONTROL', 'audit', 'Audit Log'],
    ],
  },
  { key: 'settings', label: 'Settings', icon: Settings, items: [] },
  { key: 'help', label: 'Help & Support', icon: LifeBuoy, items: [] },
];
export const titles: Record<string, string> = {
  dashboard: 'Dashboard',
  orders: 'Sales Orders',
  invoices: 'Commercial Invoices',
  customers: 'Customers',
  vendors: 'Vendors',
  'purchase-orders': 'Purchase Orders',
  bills: 'Expense Bills',
  products: 'Products',
  warehouses: 'Warehouses',
  movements: 'Stock Movements',
  stock: 'Stock Overview',
  receivables: 'Receivables',
  payables: 'Payables',
  journal: 'General Ledger',
  cash: 'Cash & Bank',
  accounts: 'Chart of Accounts',
  exceptions: 'Exception Register',
  documents: 'Document Centre',
  tasks: 'Tasks & Checklist',
  profitability: 'Profitability',
  'sales-report': 'Sales Report',
  'trial-balance': 'Trial Balance',
  users: 'Users & Roles',
  audit: 'Audit Log',
  settings: 'Settings',
  help: 'Help & Support',
  import: 'Import',
  production: 'Production',
  masters: 'Masters',
  notifications: 'Notifications',
  activity: 'Recent Activity',
  profile: 'My Profile',
};
export const routeKind = (route: string) =>
  ({
    receivables: 'invoices',
    payables: 'bills',
    'sales-report': 'invoices',
    profitability: 'journal',
    cash: 'journal',
    'trial-balance': 'journal',
    stock: 'movements',
  })[route] || route;
