import {
  LayoutDashboard,
  Quote,
  Files,
  FileText,
  Truck,
  ShoppingCart,
  Factory,
  Boxes,
  Landmark,
  MapPin,
  ClipboardCheck,
  Folder,
  Calculator,
  ChartNoAxesCombined,
  Settings,
  Users,
  PackageOpen,
  Globe,
} from 'lucide-react';
export const shipzyMenus = [
  { title: 'Dashboard', route: 'dashboard', icon: LayoutDashboard },
  { title: 'Quotation', route: 'quotations', icon: Quote },
  {
    title: 'Export Docs',
    route: 'export-docs',
    icon: Files,
    children: [
      ['proformas', 'Proforma Invoice'],
      ['pre-shipment', 'Pre-Shipment Docs'],
      ['post-shipment', 'Post-Shipment Docs'],
      ['bills-of-lading', 'BL Draft'],
      ['packing-drive', 'Packing List - Detailed'],
      ['master-quality-specifications', 'Quality Specifications'],
    ],
  },
  { title: 'Invoices', route: 'invoices', icon: FileText },
  { title: 'E-Way Bill', route: 'eway-bills', icon: Truck },
  {
    title: 'Purchase',
    route: 'purchase',
    icon: ShoppingCart,
    children: [
      ['purchase-orders', 'Purchase Order'],
      ['purchase-invoices', 'Purchase Receipt / Invoice'],
      ['supplier-advances', 'Supplier Advance'],
      ['expenses', 'Expenses'],
    ],
  },
  {
    title: 'Production',
    route: 'production',
    icon: Factory,
    children: [
      ['production-orders', 'Production Order'],
      ['production-output', 'Production Output'],
    ],
  },
  {
    title: 'Inventory',
    route: 'inventory',
    icon: Boxes,
    children: [
      ['inventory-stock-register', 'Stock Register'],
      ['machines', 'Serialized Machines'],
      ['stock-transfers', 'Stock Transfer'],
      ['warehouses', 'Warehouse'],
    ],
  },
  {
    title: 'Finance',
    route: 'finance',
    icon: Landmark,
    children: [
      ['receivables', 'Inward Payment'],
      ['payables', 'Outward Payment'],
      ['receipts', 'Receipts'],
      ['payments', 'Payments'],
      ['remittances', 'Bank Realisation'],
      ['forex', 'Forex'],
      ['ebrc', 'eBRC'],
      ['incentives', 'Export Incentives'],
    ],
  },
  { title: 'Shipment Tracking', route: 'shipments', icon: MapPin },
  { title: 'Checklist', route: 'shipment-checklist', icon: ClipboardCheck },
  { title: 'ERP Drive', route: 'documents-drive', icon: Folder },
  { title: 'Costing Sheet', route: 'costing', icon: Calculator },
  { title: 'Reports', route: 'reports', icon: ChartNoAxesCombined },
  { title: 'Master Settings', route: 'masters', icon: Settings },
  { title: 'Logistics Master', route: 'logistics-master', icon: Truck },
  {
    title: 'User',
    route: 'user-settings',
    icon: Users,
    children: [
      ['users', 'Users'],
      ['administration-permissions', 'User Roles'],
      ['profile', 'My Profile'],
    ],
  },
  {
    title: 'Domestic Docs',
    route: 'domestic',
    icon: PackageOpen,
    children: [
      ['domestic-invoices', 'Domestic Invoice'],
      ['delivery-challans', 'Delivery Challan'],
    ],
  },
  {
    title: 'Import',
    route: 'import',
    icon: Globe,
    children: [
      ['import-orders', 'Import Orders'],
      ['bill-of-entry', 'Bill of Entry'],
      ['import-costs', 'Import Costs'],
      ['import-settlements', 'Import Settlement'],
    ],
  },
];
export const shipzyTitle = (route: string) =>
  shipzyMenus.find((m) => m.route === route)?.title ||
  shipzyMenus.flatMap((m) => m.children || []).find(([r]) => r === route)?.[1];
